[build]
  # No build command needed for static site
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

# Redirect rules for better SEO and user experience
[[redirects]]
  from = "/"
  to = "/main.html"
  status = 200

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/main.html"
  status = 404

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate" 